# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/VivadoProjects/Eje_4_Ahora_Si/Eje_4_Ahora_Si.srcs/sources_1/ip/clock_16MHz/clock_16MHz.xci
# IP: The module: 'clock_16MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/VivadoProjects/Eje_4_Ahora_Si/Eje_4_Ahora_Si.gen/sources_1/ip/clock_16MHz/clock_16MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_16MHz'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/VivadoProjects/Eje_4_Ahora_Si/Eje_4_Ahora_Si.gen/sources_1/ip/clock_16MHz/clock_16MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_16MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/VivadoProjects/Eje_4_Ahora_Si/Eje_4_Ahora_Si.gen/sources_1/ip/clock_16MHz/clock_16MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_16MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/VivadoProjects/Eje_4_Ahora_Si/Eje_4_Ahora_Si.srcs/sources_1/ip/clock_16MHz/clock_16MHz.xci
# IP: The module: 'clock_16MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/VivadoProjects/Eje_4_Ahora_Si/Eje_4_Ahora_Si.gen/sources_1/ip/clock_16MHz/clock_16MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_16MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/VivadoProjects/Eje_4_Ahora_Si/Eje_4_Ahora_Si.gen/sources_1/ip/clock_16MHz/clock_16MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_16MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/VivadoProjects/Eje_4_Ahora_Si/Eje_4_Ahora_Si.gen/sources_1/ip/clock_16MHz/clock_16MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_16MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
